{"name": "Проверка повторной регистрации с повторяющимися данными", "status": "passed", "description": "Создаем пользователя с cгенерированными данными, создаем пользователя с теми же данными,     проверяем, что код ответа: 403, и текст ответа \"User already exists\"", "start": 1713017296744, "stop": 1713017297759, "uuid": "a5d061b0-bdde-4fcd-83ce-9885fa036109", "historyId": "0fe555efb5d34b6fff0d8ae363947fd3", "testCaseId": "0fe555efb5d34b6fff0d8ae363947fd3", "fullName": "tests.test_user.TestUser#test_create_two_same_user_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "DESKTOP-1VNC7DB"}, {"name": "thread", "value": "12296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}